### ISSUE TITLE
Link to change format of Help text is wrong

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/role_help#1]
**Steps to reproduce**

1. Install and enable module
2. Go to `/admin/config/people/roles/`
3. Click to Configure Role on one of the roles
4. Below the Help text field, in the description, click on the 'change this' link

**Expected result**
Goes to `/admin/config/people/roles` where the setting is
Ideally it would go to the Help text format section and un-collapse it, but I can't think of a way to do that

**Actual result**
Goes to `/admin/config/people/role-help` which doesn't exist so just loads `/admin/config/people/`

**Comment by bugfolder** [comment]
Thanks, @yorkshire-pudding!
