### ISSUE TITLE
Accommodate Backdrop core's adoption of role help descriptions

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/role_help#3]
This is a follow-on to https://github.com/backdrop/backdrop-issues/issues/5748, which is working its way through core and is likely to come out in the 1.24.0 release. When it does, Backdrop core will include role help description text on the node edit page and roles page (which have been provided by this module), but will not provide the separate Role Help listing or the Roles tab on user pages provided by this module.

So there is still a (much smaller) use case provided by this module (the extra pages).

There will also be some duplication of fields on the role edit page, which would be confusing to users. So we'll need a new version of this module that:

* Is specific to Backdrop core versions greater than or equal to the release version that includes the new core functionality;
* Removes the extra fields from the role edit form;
* Fills the module-specific pages from the core data fields, rather than the `role_help` table;
*<strike> Empties the `role_help` table. (We'll leave the table in place, though, so that it's there to be removed when the module is uninstalled.)</strike>

**Comment by bugfolder** [comment]
Notes:

* The shorter `summary` column in the `role_help` table is used to populate the new core fields `admin_description` and `description`, and will be shown by core on the user edit form and the roles config page.
* The longer `help` column has no equivalent in core, but is used on the Role Help-specific pages `user/N/roles` and `admin/people/role-help`. The module should continue to support those pages for backward compatibility.
* Since adding summaries to role descriptions on user pages has been taken over by core, we can remove the alteration of `user_profile_form`, `user_register_form`, and `role_delegation_form` from Role Help module. But should perhaps file issues in the respective module queues if they're not provided by the core functionality.

**Comment by jenlampton** [comment]
In https://github.com/backdrop/backdrop-issues/issues/5932 I have proposed removing the `admin_description` option, leaving only a single description for role help text in core. That change will make this module more valuable, since it will be providing an alternative description.
